[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["shell"]
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
hosting = "github"
install-updater = true

[dist.dependencies.apt]
pkg-config = "*"
libwayland-dev = "*"
libxkbcommon-dev = "*"
"libpipewire-0.3-dev" = "*"
libgbm-dev = "*"
libdrm-dev = "*"
libxcb1-dev = "*"
libxcb-randr0-dev = "*"
libxcb-shm0-dev = "*"
libegl1-mesa-dev = "*"
